# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Build

on: [push, pull_request]

jobs:
  build-1_4_7:
    strategy:
      matrix:
        java: [ "8" ] # Latest version
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gradle/wrapper-validation-action@v1.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: cd into directory
        run: cd ./Fabric/1.4.7/
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with: 
          name: modid
          path: Fabric/1.4.7/build/libs/*.jar
  build-1_3_2:
    strategy:
      matrix:
        java: [ "8" ] # Latest version
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gradle/wrapper-validation-action@v1.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: cd into directory
        run: cd ./Fabric/1.3.2/
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with: 
          name: modid
          path: Fabric/1.3.2/build/libs/*.jar

